{% set name = "pydantic-sqlalchemy" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydantic-sqlalchemy-{{ version }}.tar.gz
  sha256: 82035d4b3f8019b2e3f070b7ce3f764a30ada03b632c1b5df54dd4c49438de6a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0
    - sqlalchemy >=1.3.16,<2.0.0
    - pydantic >=1.5.1

test:
  imports:
    - pydantic_sqlalchemy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tiangolo/pydantic-sqlalchemy
  summary: Tools to convert SQLAlchemy models to Pydantic models
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
